### ISSUE TITLE
get doesn't seem to work when in nested directories

### ISSUE THREAD

**Issue by knackjax** [jdhirst1/ncc_cli#2]
ncc get mbs/tipper_20190911.bundle

Traceback (most recent call last):
  File "/usr/bin/ncc", line 9, in <module>
    load_entry_point('ncc-cli==0.0.2', 'console_scripts', 'ncc')()
  File "build/bdist.linux-x86_64/egg/ncc_cli/ncc_cli.py", line 382, in main
  File "build/bdist.linux-x86_64/egg/ncc_cli/ncc_cli.py", line 191, in get
  File "build/bdist.linux-x86_64/egg/ncc_cli/ncc_cli.py", line 70, in dl_getsize
  File "/usr/lib/python2.7/site-packages/owncloud/owncloud.py", line 379, in file_info
    res = self._make_dav_request('PROPFIND', path, headers={'Depth': '0'})
  File "/usr/lib/python2.7/site-packages/owncloud/owncloud.py", line 1679, in _make_dav_request
    raise HTTPResponseError(res)
owncloud.owncloud.HTTPResponseError: HTTP error: 404

**Comment by jdhirst** [comment]
Thanks for bringing this forward! This has been resolved by commit 7267cc2, we were using lpath instead of rpath for get requests, which worked fine for current wd, but failed for nested remote directories. @knackjax
