### ISSUE TITLE
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 28, column 145

### ISSUE THREAD

**Issue by arthurzenika** [jdhirst1/ncc_cli#6]
When entering a wrong URL (forgot to remove the apps/files in the link) I get a traceback

```
Server URI: https://nextcloud.example.org/apps/files/
Username: arthur
Password: 
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/ncc-cli/bin/ncc", line 8, in <module>
    sys.exit(main())
  File "/home/arthur/.virtualenvs/ncc-cli/lib/python3.8/site-packages/ncc_cli/ncc_cli.py", line 328, in main
    ls('/')
  File "/home/arthur/.virtualenvs/ncc-cli/lib/python3.8/site-packages/ncc_cli/ncc_cli.py", line 117, in ls
    connect()
  File "/home/arthur/.virtualenvs/ncc-cli/lib/python3.8/site-packages/ncc_cli/ncc_cli.py", line 66, in connect
    session.login(cfguser,cfgpass)
  File "/home/arthur/.virtualenvs/ncc-cli/lib/python3.8/site-packages/owncloud/owncloud.py", line 354, in login
    self._update_capabilities()
  File "/home/arthur/.virtualenvs/ncc-cli/lib/python3.8/site-packages/owncloud/owncloud.py", line 1798, in _update_capabilities
    tree = ET.fromstring(res.content)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 28, column 145
```

It would be nice for it to display an error message. And maybe a suggestion of fix.

**Comment by jdhirst** [comment]
Indeed, we could add a try except statement there, definitely! Would you like to do a pull request for this?

**Comment by jdhirst** [comment]
@arthurlogilab I added more exception handling in 0.0.6, try that. It should not return a traceback now
